"""table_master.py -- one table across every model variant, dataset and feature family.

Consolidates results scattered across a dozen JSON files into a single publication table:
variant, hyperparameters/complexity, in-distribution error, every external dataset, the
calibration-anchor requirement, and the top features by permutation importance.

Two columns exist to stop the reader over-reading the OOD numbers:

  mean floor   the error of predicting that dataset's own mean BP. On every external set the
               best model merely matches this, so cross-dataset "wins" are not evidence of
               transferable signal.
  anchors@     how many per-subject calibration anchors a variant needs to reach the reference
               error. This is the axis where models DO separate, and the deployable question
               for a device.

    python table_master.py            # markdown to stdout + docs/table_master.md
    python table_master.py --csv      # also write a CSV
"""
import argparse
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
OUT = ROOT / "RESULTS_TABLES.md"

# error of predicting each external set's own mean DBP (see the mean-predictor baseline)
MEAN_FLOOR = {"ID": 9.43, "MIMIC-BP": 10.22, "BCG": 7.41, "Sensors": 8.23,
              "UCI2": 8.59, "PPG-BP": 8.84}
OOD_SETS = ["MIMIC-BP", "BCG", "Sensors", "UCI2", "PPG-BP"]


def load(name):
    p = DATA / name
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text())
    except Exception:
        return {}


def fmt(v, nd=2):
    if v is None or (isinstance(v, float) and not np.isfinite(v)):
        return "--"
    return f"{v:.{nd}f}"


def table_variants():
    """Model variants: complexity, ID error, OOD error, against the mean floor."""
    ood = load("gbm_variants_ood.json")
    opt = load("gbm_optuna.json")
    rows = []
    complexity = {
        "default (83 feat)": "800 trees x 63 leaves",
        "Optuna-tuned (83 feat)": "479,790 leaves (tuned)",
        "SFS-selected (19 feat)": "50,400 leaves",
        "single tree (12 feat)": "1 tree, 32 leaves",
    }
    for name, v in ood.items():
        if not isinstance(v, dict):
            continue
        r = {"variant": name, "complexity": complexity.get(name, ""),
             "n_feat": v.get("n_feat"), "ID": v.get("ID")}
        for s in OOD_SETS:
            r[s] = v.get(s)
        rows.append(r)
    for name, v in opt.items():
        if isinstance(v, dict) and "val_mae" in v and name not in ood:
            rows.append({"variant": name, "complexity": "", "n_feat": v.get("n_feat"),
                         "ID": v.get("test_mae") or v.get("val_mae")})
    return rows


def table_families():
    """Feature families: ID/OOD accuracy and calibration-anchor requirement."""
    fam = load("gbm_families.json")
    cal = load("calib_families.json")
    ref = None
    if "all 83 (waveform)" in cal:
        ref = cal["all 83 (waveform)"]["curve"].get("20")
    ks = ["0", "1", "2", "3", "5", "10", "20"]
    rows = []
    for name, v in cal.items():
        if name.startswith("_") or not isinstance(v, dict) or "curve" not in v:
            continue
        c = v["curve"]
        hit = next((int(k) for k in ks if ref is not None and c.get(k, 9e9) <= ref), None)
        f = fam.get(name.split(" +")[0].split(" /")[0], {})
        rows.append({"family": name, "n_feat": v.get("n_feat"),
                     "k=0": c.get("0"), "k=5": c.get("5"), "k=20": c.get("20"),
                     "anchors_to_ref": hit,
                     "anchor_value": v.get("anchor_value"),
                     "ID_uncal": f.get("ID") if isinstance(f, dict) else None})
    rows.sort(key=lambda r: (r["k=20"] if r["k=20"] is not None else 9e9))
    return rows, ref


def table_importance(top=12):
    cal = load("calib_families.json")
    imp = cal.get("_perm_importance_k5", {})
    return sorted(imp.items(), key=lambda kv: -kv[1])[:top], cal.get("_base_k5")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", action="store_true")
    args = ap.parse_args()

    md = ["# Consolidated result tables",
          "",
          "Generated by `table_master.py` from the JSON files in `data/`. DBP throughout.",
          "",
          "All LightGBM variants are trained on the **full** PulseDB VitalDB CalFree split: "
          "396,000 train segments from 1,100 subjects, 57,600 test segments from 144 "
          "subject-disjoint held-out subjects, 83 features.",
          ""]

    # ---- table 1: model variants -------------------------------------------
    md += ["## Table 1 — model variants across datasets", "",
           "| variant | complexity | n feat | ID | " + " | ".join(OOD_SETS) + " |",
           "|---|---|---|---|" + "---|" * len(OOD_SETS)]
    for r in table_variants():
        md.append(f"| {r['variant']} | {r.get('complexity','')} | {r.get('n_feat','--')} | "
                  f"{fmt(r.get('ID'))} | "
                  + " | ".join(fmt(r.get(s)) for s in OOD_SETS) + " |")
    md += ["| **predict that set's mean** | -- | 0 | "
           f"{MEAN_FLOOR['ID']:.2f} | "
           + " | ".join(f"{MEAN_FLOOR[s]:.2f}" for s in OOD_SETS) + " |", ""]
    md += ["The final row is the key comparison: on **every** external set the best model merely "
           "matches the error of predicting that dataset's own mean. Cross-dataset differences "
           "between variants are therefore not evidence of transferable signal.", ""]

    # ---- table 2: feature families + calibration ---------------------------
    fam_rows, ref = table_families()
    md += ["## Table 2 — feature families and calibration burden", "",
           f"Anchors needed to reach the 83-feature waveform model at 20 anchors "
           f"({fmt(ref)} mmHg). Anchors are chosen at random per subject, not the first *k*: "
           "first-*k* anchors sit adjacent in time to the scored segments and absorb local drift "
           "as well as per-subject offset, which flatters the result.", "",
           "| feature family | n feat | k=0 | k=5 | k=20 | anchors to reach ref | anchor value |",
           "|---|---|---|---|---|---|---|"]
    for r in fam_rows:
        md.append(f"| {r['family']} | {r['n_feat']} | {fmt(r['k=0'])} | {fmt(r['k=5'])} | "
                  f"{fmt(r['k=20'])} | {r['anchors_to_ref'] if r['anchors_to_ref'] is not None else '>20'} | "
                  f"{fmt(r['anchor_value'])} |")
    md += ["", "*anchor value* = MAE(k=0) - MAE(k=5), i.e. how much of a family's usefulness only "
           "becomes accessible after calibration.", ""]

    # ---- table 3: top features ---------------------------------------------
    imp, base = table_importance()
    md += ["## Table 3 — top features by permutation importance", "",
           f"Computed on the **calibrated** error (per-subject offset fitted on 5 anchors, "
           f"base {fmt(base)} mmHg), so features are ranked by their contribution to "
           "post-calibration accuracy rather than to raw accuracy.", "",
           "| rank | feature | Δ MAE when permuted (mmHg) |", "|---|---|---|"]
    for i, (k, v) in enumerate(imp, 1):
        md.append(f"| {i} | `{k}` | {v:+.3f} |")
    md += ["", "Age dominates by a factor of three over the next feature. The PAT family is "
           "absent from the top ranks: `pat_foot` scores +0.002, and `pat_peak` and `xcorr_lag` "
           "are negative.", ""]

    OUT.write_text("\n".join(md), encoding="utf-8")
    # the tables carry en-dashes and Greek letters; a cp1252 console would raise on them
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    print("\n".join(md))
    print(f"\n[done] {OUT.name}")

    if args.csv:
        import csv
        with open(ROOT / "data" / "table_master.csv", "w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow(["variant", "complexity", "n_feat", "ID"] + OOD_SETS)
            for r in table_variants():
                w.writerow([r["variant"], r.get("complexity", ""), r.get("n_feat"),
                            r.get("ID")] + [r.get(s) for s in OOD_SETS])
        print("[done] data/table_master.csv")


if __name__ == "__main__":
    main()
